### ISSUE TITLE
Using the wrong timezone

### ISSUE THREAD

**Issue by MrKoopie** [metaregistrar/whmcs#1]
https://github.com/metaregistrar/whmcs/blob/0d351502aa36ac3a6bb088d8f437c2ffbb7763b2/modules/registrars/Metaregistrar/classes/metaregistrar-epp-client/autoloader.php#L2

I understand that the timezone is synchronised to prevent mismatches between the real dates. However, setting the global WHMCS timezone to UTC globally is not the solution. Instead, I recommend converting the dates where appropriate in the code rather than changing the global timezone.

Changing the timezone has multiple problems:

- Activities are logged with an incorrect time.
- Emails are logged with an incorrect time.
- Tickets are logged with an incorrect time.
- Cron runs at the incorrect time.
- etc.

**Comment by metaregistrar** [comment]
The timezone setting is part of the EPP package that is used, not part of the WHMCS implementation. Feel free to remove it when it is in the way.

The reason why it is in the EPP package, is that when connecting to EPP services around the world, it is useful to have the same timestamp everywhere. Most companies that run EPP services use UTC for timestamping EPP messages because UTC has no summer/wintertime (hence no double timestamps when the time changes to summer or wintertime) and it is a useful time setting when you want to compare a message sent by a client with a message received by a server.

**Comment by MrKoopie** [comment]
@metaregistrar I understand the reason as we build domain connectors plenty of times. To overcome this problem, the date received and send to the API should get converted from the current timezone to the UTC timezone. Changing the global timezone causes different problems for other parts of the program that rely on correct time reporting. Logs are incorrect as well. I understand that you are interacting with a package, but that should not matter.

For now, I have removed this on our side. But the best solution would be to have proper implementation without changing the global timezone. The Carbon package (https://carbon.nesbot.com/docs/) is a perfect tool and can save some time.
